Functions:
  filter: .Functions[] | (. + .VpcConfig) | del(.VpcConfig)
  fields:
    - FunctionName
    - Runtime
    - MemorySize
    - CodeSize
    - PackageType
    - LastModified
    - Handler
    - Role
    - VpcId
    - SubnetIds
Reservations:
  filter: .Reservations[] | .OwnerId as $OwnerId | .Instances[] | (. + { $OwnerId })
  fields:
    - OwnerId
    - InstanceId
    - tag:Name
    - ImageId
    - InstanceId
    - IntanceType
    - KeyName
    - LaunchTime
    - PlatformDetails
    - SubnetId
    - VpcId
    - PublicIpAddress
    - PrivateIpAddress
Vpcs:
  filter: .Vpcs[] | (. + .BlockPublicAccessStates) | del(.BlockPublicAccessStates)
  fields:
    - VpcId
    - tag:Name
    - CidrBlock
    - IsDefault
    - State
    - DhcpOptionsId
Subnets:
  filter: >-
    .Subnets[] |
    (. + .PrivateDnsNameOptionsOnLaunch + .BlockPublicAccessStates) |
    del(.PrivateDnsNameOptionsOnLaunch) | del(.BlockPublicAccessStates)
  fields:
    - SubnetId
    - tag:Name
    - VpcId
    - CidrBlock
    - AvailableIpAddressCount
    - AvailabilityZone
VpcEndpoints:
  fields:
    - VpcEndpointId
    - tag:Name
    - VpcEndpointType
    - VpcId
    - ServiceName
    - PrivateDnsEnabled
    - OwnerId
ProductViewDetails: # servicecatalog search-products-as-admin
  filter: .ProductViewDetails[] | (. + .ProductViewSummary) | del(.ProductViewSummary)
